print(True or False)
print(True or False and False and False )
print(False and True)
print(True or False and False)
print(False and True and False) 
print(True and True or True)
print(False or True or True)
print(False or True or False)
print(True or True or True or True)
print(False and True or True or True)